plugins {
    id 'fabric-loom' version '1.6.12'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.20.1"
    mappings "net.fabricmc:yarn:1.20.1+build.10:v2"

    modImplementation "net.fabricmc:fabric-loader:0.15.11"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.1+1.20.1"
}

java {
    withSourcesJar()
    withJavadocJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

loom {
    splitEnvironmentSourceSets = true

    mods {
        "fabric-ai-animation" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

tasks.processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", "1.20.1"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
               "minecraft_version": "1.20.1"
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 17
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
